# These are supported funding model platforms

github: [czy1024] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: czy1024 # Replace with a single Patreon username
# open_collective: czy1024 # Replace with a single Open Collective username
# ko_fi: czy1024 # Replace with a single Ko-fi username
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
# liberapay: czy1024 # Replace with a single Liberapay username
# issuehunt: # Replace with a single IssueHunt username
# otechie: # Replace with a single Otechie username
custom: ['https://www.isczy.tk/luna-linux-conf/', 'https://www.isczy.tk/blog'] # Replace with up to 4 custom sponsorship URLs e.g., 
